// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelter.Models;

namespace Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    [Migration("20210611234439_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdoptionStatus")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ApproximateAge")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FluffinessLevel")
                        .HasColumnType("int");

                    b.Property<bool>("HasShots")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AdoptionStatus = "unadopted",
                            ApproximateAge = 0,
                            Biography = "Likes green apples, long walks on the beach, and eyepatches",
                            Breed = "Pitbull Mix",
                            FluffinessLevel = 6,
                            HasShots = true,
                            Name = "Captian Furbossa",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            AdoptionStatus = "pending",
                            ApproximateAge = 0,
                            Biography = "Likes looking out windows, chasing lasers, and adventuring into laundry baskets",
                            Breed = "Norwegian Forest Cat",
                            FluffinessLevel = 10,
                            HasShots = true,
                            Name = "Pawme Amidala",
                            Type = "cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            AdoptionStatus = "unadopted",
                            ApproximateAge = 0,
                            Biography = "Likes sniffing, climbing on everything, and intelligent converstaions",
                            Breed = "Brussels Griffon Mix",
                            FluffinessLevel = 7,
                            HasShots = true,
                            Name = "Wicket",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            AdoptionStatus = "unadopted",
                            ApproximateAge = 0,
                            Biography = "Likes hiding things that don't belong to him, barking orders, and naps",
                            Breed = "unknown",
                            FluffinessLevel = 4,
                            HasShots = true,
                            Name = "Admiral Ackbark",
                            Type = "dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            AdoptionStatus = "unadopted",
                            ApproximateAge = 0,
                            Biography = "Likes causing chaos, destroying everything in sight, and belly rubs",
                            Breed = "Birman",
                            FluffinessLevel = 6,
                            HasShots = true,
                            Name = "Catsian",
                            Type = "cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
